### ISSUE TITLE
Question about COCO pretrained model

### ISSUE THREAD

**Issue by suilin0432** [hologerry/SoCo#12]
Thank you for your great job!
I noticed that you added the result with the model which was pretrained on MS-COCO dataset recently in the revised version.
Could you please upload such a model or release the training script if it is convenient for you?
Thank you so much~ Looking forward to your reply.

**Comment by hologerry** [comment]
The models pretrained on MS-COCO are uploaded to the Google Drive folder, please check the folders: `pretrain/SoCo_FPN_COCO_100ep` and `pretrain/SoCo_FPN_COCO_530ep`.
Thanks!
