### ISSUE TITLE
What are the format requirements for the data?

### ISSUE THREAD

**Issue by mitming** [hologerry/SoCo#17]
Hi @hologerry , 

Thanks for your contribution, but I'm very confused about the data format requirements of this code, there doesn't seem to be any explanation.

I construct the data format like this:
```
| imagenet
| ---- train
| --------n01440766
| ---- val
```

However, when I try to run the code
```
bash ./tools/SoCo_FPN_100ep.sh
```

There is an error and I have no idea how to fix it:
```
FileNotFoundError: [Errno 2] No such file or directory: './data/imagenet/train_map.txt'
```

Could you please refine the README and provide the available data formats?

**Comment by linusericsson** [comment]
Hi @mitming,

I'm not one of the authors but I've gone through this same painful process and have some info!
When running the selective search scripts I had the ImageNet data formatted in the same way you describe (i.e. its default structure). However, when pre-training models the SoCo code here expects the ImageNet data to be in a ZIP format. This means I have one `train.zip` file that contains all class folders and images (without the top folder `train/`).

Then I needed to search around for this train_map.txt file that didn't exist. I eventually tried to generate the file using the code from here https://github.com/microsoft/CNTK/issues/2091#issuecomment-313701629.
I think this is what solved it for me in the end.

Hope this helps,
Linus

**Comment by mitming** [comment]
> Hi @mitming,
> 
> I'm not one of the authors but I've gone through this same painful process and have some info! When running the selective search scripts I had the ImageNet data formatted in the same way you describe (i.e. its default structure). However, when pre-training models the SoCo code here expects the ImageNet data to be in a ZIP format. This means I have one `train.zip` file that contains all class folders and images (without the top folder `train/`).
> 
> Then I needed to search around for this train_map.txt file that didn't exist. I eventually tried to generate the file using the code from here [microsoft/CNTK#2091 (comment)](https://github.com/microsoft/CNTK/issues/2091#issuecomment-313701629). I think this is what solved it for me in the end.
> 
> Hope this helps, Linus

Hi @linusericsson ,

Thank you for your reply, it has benefited me a lot.

Although the data reading problem can be solved by your solution, however, I still can't run the code successfully, and there seems to be other bugs of the code.

Can you please tell me if you can run the code here properly? If so, have you made any changes?

**Comment by linusericsson** [comment]
Hi @mitming 

Yes, I think I remember having some similar bugs when first trying to run the code.

I believe the error below can be fixed by casting x1 and x2 into integers: `random.randint(int(x1), int(x2))`
```
/home/code/repos/SoCo/contrast/data/transform_ops.py(362)__call__()
-> center_cut_x = random.randint(x1, x2)
*** ValueError: non-integer stop for randrange()
```

Later, you might have the same problem I did with APEX mixed-precision. For me, the optimization level O1 did not work at first. I tried O2 instead and that ran but gave lower downstrream performance. I eventually patched APEX which fixed the O1 setting.

Hope this helps,
Linus

**Comment by isgeng** [comment]
> Hi @hologerry ,
> 
> Thanks for your contribution, but I'm very confused about the data format requirements of this code, there doesn't seem to be any explanation.
> 
> I construct the data format like this:
> 
> ```
> | imagenet
> | ---- train
> | --------n01440766
> | ---- val
> ```
> 
> However, when I try to run the code
> 
> ```
> bash ./tools/SoCo_FPN_100ep.sh
> ```
> 
> There is an error and I have no idea how to fix it:
> 
> ```
> FileNotFoundError: [Errno 2] No such file or directory: './data/imagenet/train_map.txt'
> ```
> 
> Could you please refine the README and provide the available data formats?

Hi @mitming
I also encountered this problem. But unpacked ImageNet data is too large for me. 
Is it convenient for you to send this file `train_map.txt` to my email `2229793224@qq.com`? 
Thanks!
