### ISSUE TITLE
jitter_prob is alwayws 0

### ISSUE THREAD

**Issue by haohang96** [hologerry/SoCo#2]
It seems that **jitter_prob** is not initialized by **args.jitter_prob** in **contrast/data/__init__.py**, and it will always be the default value 0. Is it because the BoxJitter operation has a trivial improvement according to Table4 in the paper and we can ignore it?

**Comment by hologerry** [comment]
Hi, Thanks for pointing out this. It's a typo, during our experiments, most of the arguments are just hardcoded without the parameters passing. It is missed when cleaning the code and preparing the public release.
The `jitter_prob` of the full model is set as stated in the paper.
I have updated the code.
Thanks again.
