### ISSUE TITLE
Where is the Base-RCNN-C4-BN.yaml file?

### ISSUE THREAD

**Issue by suilin0432** [hologerry/SoCo#6]
Thanks for your great job~
In SoCo/detectron2_configs/R_50_C4_1x.yaml, Base-RCNN-C4-BN.yaml was refered.
https://github.com/hologerry/SoCo/blob/624a70d6932a185f658173adf6e0862e69990501/detectron2_configs/R_50_C4_1x.yaml#L1
However, I do not find the Base-RCNN-C4-BN.yaml under SoCo/detectron2_configs/ folder. Could you please upload this file or tell me details about such a setting?
Thanks a lot, looking forward to your reply~

**Comment by hologerry** [comment]
Thanks for pointing it out.
This file is now provided in commit 2be1229ab3d9ec8e72537a7c519f51dc03450ebb.
