### ISSUE TITLE
bounding box data after selective search is too large to store

### ISSUE THREAD

**Issue by antony0621** [hologerry/SoCo#8]
hi hologerry,

after using your 3-step selective search tool, I found the obtained bbox data is about 2.3T for imagenet, which is hard to store. Is this data size normal or I need some other important operation to filter the bbox?

**Comment by hologerry** [comment]
Hi @antony0621 , looks like you are missing something...
On my machine, the `.json` file is only 1.1G after post processing.

**Comment by antony0621** [comment]
> Hi @antony0621 , looks like you are missing something... On my machine, the `.json` file is only 1.1G after post processing.

Thanks for your reply. So I guess the obtained .pkl file should be deleted after the post-processing.

**Comment by hologerry** [comment]
Yeah, remove `.pkl` files when you obtained the `.json` file.

**Comment by liyz15** [comment]
Even as intermediate result, 2.3T is still too larget. Is there any chance you can share the processed json for ImageNet?

**Comment by hologerry** [comment]
The `.json` file is shared in the Google drive folder now. Thanks!
